<?php

declare(strict_types=1);

namespace Tests\Unit\Domain\Report\Events;

use App\Domain\GitLab\Models\Branch;
use App\Domain\GitLab\Models\Commit;
use App\Domain\Narrative\Actions\GenerateNarrativesForReport;
use App\Domain\Narrative\Listeners\GenerateNarrativesOnReportGenerated;
use App\Domain\Narrative\Services\NarrativeSupport;
use App\Domain\Report\Actions\GenerateReport;
use App\Domain\Report\Enums\ReportStatus;
use App\Domain\Report\Queries\GetCommitsForDate;
use App\Domain\Report\Queries\GetTaskIdsFromCommits;
use App\Domain\Report\Events\ReportGenerated;
use App\Domain\Report\Models\Report;
use App\Domain\Report\Models\ReportTask;
use App\Domain\Shared\ValueObjects\DateRange;
use App\Domain\Narrative\Services\LlmProviderInterface;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Tests\Mocks\MockLlmProvider;
use Tests\TestCase;

final class ReportGeneratedTest extends TestCase
{
    use RefreshDatabase;

    public function test_generate_report_dispatches_report_generated_event(): void
    {
        // GIVEN — a commit exists within the requested date range
        Event::fake([ReportGenerated::class]);
        $branch = Branch::factory()->create();
        Commit::factory()->create([
            'branch_id'    => $branch->id,
            'committed_at' => '2026-03-10 10:00:00',
        ]);
        $action = new GenerateReport(new GetCommitsForDate(), new GetTaskIdsFromCommits());

        // WHEN — the GenerateReport action is invoked
        $report = $action('daily', new DateRange('2026-03-10', '2026-03-10'));

        // THEN — a ReportGenerated event is dispatched carrying the correct report
        Event::assertDispatched(ReportGenerated::class, function (ReportGenerated $event) use ($report): bool {
            return $event->report->id === $report->id;
        });
    }

    public function test_listener_calls_generate_narratives(): void
    {
        // GIVEN — a draft report with a task and LLM mock bound in the container
        $this->app->bind(LlmProviderInterface::class, MockLlmProvider::class);

        $report = Report::factory()->draft()->create();
        ReportTask::factory()->create(['report_id' => $report->id]);

        $mockLlm = new MockLlmProvider();
        $listener = new GenerateNarrativesOnReportGenerated(
            new GenerateNarrativesForReport($mockLlm, new NarrativeSupport())
        );
        $event = new ReportGenerated($report);

        // WHEN — the listener handles the ReportGenerated event
        $listener->handle($event);

        // THEN — the LLM provider was called to generate narrative for the task
        $this->assertCount(1, $mockLlm->narrativeRequests);
        // AND — the report status was updated to Generated by the action
        $report->refresh();
        $this->assertSame(ReportStatus::Generated, $report->status);
    }
}
